apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
stringData:
  datasource-url: jdbc:postgresql://postgres-service:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}
  datasource-username: {{ .Values.postgres.username }}
  datasource-password: {{ .Values.postgres.password }}